name: snapshot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          #settings-path: ${{ github.workspace }} # location for the settings.xml
          #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
      - name: Build with Maven
        run: ./mvnw package

      - name: Add private key to keyring
        run: |
          echo "${PRIVATE_KEY}" > private.key
          gpg --import --batch private.key
        env:
          PRIVATE_KEY: ${{ secrets.GPG_SECRET_KEY }}

      - name: Publish to repository
        run: ./mvnw deploy -s settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
